import random;

class AllResponse:
    #Response String
    allResponse = {};
    allResponse["help"] = "You can see what I can do listed on the Carousel bloew. I am case-insensitive bot so no worries about your inputs. Tap on each item to start the wizard of each feature."
    allResponse["helpspec"] = "Type \"spec\" for wizard or use or use \nspec [productname] [model] \n ex: \n - spec 3par 8200\n - spec nimble af20"
    allResponse["helplookup"] =  "Type \"lookup\" for wizard or use or use \nlookup [productname] [attribute] [value] \n ex: \n - lookup intel core 20\n - lookup amd clock 3.3"
    allResponse["helptips"] = [ "Ask me for 'help' to see what I can do for you",
    							"Want to learn how to talk to me?\nAsk me for 'help'.",
    							"Ask for 'help' to see how smart I am."]

    allResponse["hello"] = [        "Hello there , ",
    							    "Hello, ",
    							     "What's up, ",
    							     "Good day, ",
    							     "Hi, ",
     							    "May I help you, ",
    							    "Greetings, ",
    							    "How can I help you, "]
    allResponse["thank"] = [        "You are always welcome.",
    							    "With pleasure.",
    							    "I am glad to be your service.",
    							    "My pleasure.",
    							    "You can ask me for help anytime."]
    allResponse["bye"] = [          "I'll be back, ",
    							     "Bye bye, ",
    							     "So longgg, ",
    							     "Hasta la vista, ",
    							     "Sayonara, ",
    							     "Life is too short to say goodbye, "]
    allResponse["yourname"] = [     "Don'you see my name above?",
    							    "My name is Uvuvwevwevwe Onyetenyevwe Ugwemubwem Ossas",
    							    "I am the one called YOU KNOW WHO.",
    							    "I am the Dark Lord.",
    							    "Kimino na wa!"]
    allResponse["whatyoudo"] = [    "I am chatting with you,seriously.",
    							    "Texting texting texting texting texting texting texting",
    							    "Chit chat! I am Chit-chatting.",
    							    "I am talking with you.",
    							    "I have no idea what I am doing right now."]
    allResponse["what"] = [         "What !??",
    							    "Wattttt?",
    							    "What is what ?",
    							    "What is a pronoun to ask for information specifying something.",
    							    "Duhhhh",
    							    "What are you talking about?"]
    allResponse["where"] = [        "Where is a matter of place not a matter of time.",
    							    "This universe is really big don't you think?",
    							    "That's use to ask in or to what place or position",
    							    "Where is what?",
    							    "I don't know. Duhhh!"]
    allResponse["when"] = [         "When is a matter of time not a matter of place.",
    							    "This universe heat death is very long.",
    							    "At any moment now.",
    							    "When is what?",
    							    "How do I know?",
    							    "I don' know. Duhhh!"]
    allResponse["why"] = [          "Because it is my demand.",
    							    "Because it is an order from god. And I am your god now.",
    							    "Do not seek for a reason. Everything has its own purpose.",
    							    "Because nothing is true. Everything is permitted.",
    							    "Why should I know?"]
    allResponse["whoareyou"] = [    "I am your worst nightmare.",
    							    "I am a creature called Homosapiean",
    							    "I am Batman!",
    							    "I am your shadow.",
    							    "I am you."]
    allResponse["who"] = [          "Who ??",
    							    "Each and Everyone.",
    							    "No body.",
    							    "Just you and me my friend.",
    							    "Why should I know?",
    							    "I don't know. Duhhh!"]
    allResponse["howareyou"] = [    "No. Not good. NOT GOOD!",
    							    "I'm fine thank you and you?",
    							    "I felt terrible. ",
    							    "Never been this good. ",
    							    "I feel selfless. "]
    allResponse["how"] = [          "I do not know how.",
    							    "How sould I know?",
    							    "No idea. Duhhh"]
    allResponse["canyou"] = [       "No. I can't do somthing like that.",
    							    "No. I don't have an ability to do that",
    							    "I dont have time for that !"]
    allResponse["really"] = [       "Indeed,.",
    							    "Oh sure.",
    							    "Yes!",
    							     "It is!",
    							     "Defenately"]
    allResponse["joke"] = [         "I would tell you a chemistry joke but I know I wouldnt get a reaction.",
    							    "Why dont some couples go to the gym?\nBecause some relationships dont work out.",
    							    "I wondered why the baseball was getting bigger. Then it hit me.",
    							    "Have you ever tried to eat a clock?\nIt is very time consuming.",
    							    "The experienced carpenter really nailed it,but the new guy screwed everything up.",
    							    "Did you hear about the guy whose whole left side was cut off?\nHe is all right now.",
    							    "Yesterday I accidentally swallowed some food coloring. The doctor says I am OK,but I feel like I have dyed a little inside.",
    							    "I wasnt originally going to get a brain transplant,but then I changed my mind.",
    							    "A guy was admitted to hospital with 8 plastic horses in his stomach. His condition is now stable..",
    							    "If a wild pig kills you,does it mean you’ve been boared to death?",
    							    "You cry,I cry,…you laugh,I laugh…you jump off a cliff I laugh even harder!!",
    							    "Never steal. The government hates competition.",
    							    "Doesn’t expecting the unexpected make the unexpected expected?",
    							    "Practice makes perfect but then nobody is perfect so what’s the point of practicing?",
    							    "Everybody wishes they could go to heaven but no one wants to die.",
    							    "Why are they called apartments if they are all stuck together?",
    							    "DON’T HIT KIDS!!! No,seriously,they have guns now.",
    							    "Save paper,don’t do home work.",
    							    "Do not drink and drive or you might spill the drink.",
    							    "Life is Short – Talk Fast!",
    							    "Why do stores that are open 24/7 have locks on their doors?",
    							    "When nothing goes right,Go left.",
    							    "Save water ,do not shower.",
    							    "A Lion would never cheat on his wife but a Tiger Wood.",
    							    "Why do they put pizza in a square box?",
                                    "Why did Adele cross the road?\nTo say hello from the other side.",
                                    "What kind of concert only costs 45 cents?\nA 50 Cent concert featuring Nickelback.",
                                    "What did the grape say when it got crushed?\nNothing, it just let out a little wine.",
                                    "I want to be cremated as it is my last hope for a smoking hot body.",
                                    "Time flies like an arrow. Fruit flies like a banana.",
                                    "To the guy who invented zero, thanks for nothing.",
                                    "I had a crazy dream last night! I was swimming in an ocean of orange soda. Turns out it was just a ""Fanta sea.",
                                    "A crazy wife says to her husband that moose are falling from the sky. The husband says, it’s ""reindeer.",
                                    "Ladies, if he can’t appreciate your fruit jokes, you need to let that mango.",
                                    "Geology rocks but Geography is where it’s at!",
                                    "What was Forrest Gump’s email password?\n1forrest1",
                                    "Did you hear about the restaurant on the moon?\nI heard the food was good but it had no atmosphere.",
                                    "Can February March?\nNo, but April May.",
                                    "Need an ark to save two of every animal?\nI noah guy.",
                                    "I don’t trust stairs because they’re always up to something.",
                                    "Smaller babies may be delivered by stork but the heavier ones need a crane.",
                                    "My grandpa has the heart of the lion and a lifetime ban from the zoo.",
                                    "Why was Dumbo sad?\nHe felt irrelephant.",
                                    "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
                                    "I lost my mood ring and I don’t know how to feel about it!",
                                    "Yesterday, I accidentally swallowed some food coloring. The doctor says I’m okay, but I feel like ""I’ve dyed a little inside.",
                                    "So what if I don’t know what apocalypse means?\nIt’s not the end of the world!",
                                    "My friend drove his expensive car into a tree and found out how his Mercedes bends.",
                                    "Becoming a vegetarian is one big missed steak.",
                                    "I was wondering why the ball was getting bigger. Then it hit me.",
                                    "Some aquatic mammals at the zoo escaped. It was otter chaos!",
                                    "Never trust an atom, they make up everything!",
                                    "Waking up this morning was an eye-opening experience.",
                                    "Long fairy tales have a tendency to dragon.",
                                    "What do you use to cut a Roman Emperor’s hair?\nCeasers.",
                                    "The Middle Ages were called the Dark Ages because there were too many knights.",
                                    "My sister bet that I couldn’t build a car out of spaghetti. You should’ve seen her face when I ""drove pasta.",
                                    "I made a pun about the wind but it blows.",
                                    "Never discuss infinity with a mathematician, they can go on about it forever.",
                                    "I knew a guy who collected candy canes, they were all in mint condition.",
                                    "My wife tried to apply at the post office but they wouldn’t letter. They said only mails work here.",
                                    "My friend’s bakery burned down last night. Now his business is toast.",
                                    "Getting the ability to fly would be so uplifting.",
                                    "It’s hard to explain puns to kleptomaniacs because they always take things literally.",
                                    "Two windmills are standing in a wind farm. One asks, 'What’s your favorite kind of music?' The other says, 'I’m a big metal fan.'",
                                    "I can’t believe I got fired from the calendar factory. All I did was take a day off!",
                                    "England doesn’t have a kidney bank, but it does have a Liverpool.",
                                    "What do you call the wife of a hippie?\nA Mississippi.",
                                    "A cross-eyed teacher couldn’t control his pupils.",
                                    "She had a photographic memory, but never developed it.",
                                    "I wasn’t originally going to get a brain transplant, but then I changed my mind.",
                                    "There was a kidnapping at school yesterday. Don’t worry, though – he woke up!",
                                    "What do you get when you mix alcohol and literature?\nTequila mockingbird.",
                                    "What washes up on tiny beaches?\nMicrowaves.",
                                    "I hate how funerals are always at 9 a.m. I’m not really a mourning person.",
                                    "What’s the difference between a poorly dressed man on a bicycle and a nicely dressed man on a ""tricycle?\nA tire.",
                                    "The guy who invented the door knocker got a no-bell prize.",
                                    "German sausage jokes are just the wurst.",
                                    "What do you call an alligator in a vest?\nAn investigator.",
                                    "What do you call the ghost of a chicken?\nA poultry-geist.",
                                    "How does Moses make coffee?\nHebrews it.",
                                    "The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t ""make any cents.",
                                    "Sure, I drink brake fluid. But I can stop anytime!",
                                    "What do you call a man with no arms and no legs stuffed in your mailbox?\nBill.",
                                    "Somebody stole all my lamps. I couldn’t be more de-lighted!",
                                    "I bought a boat because it was for sail.",
                                    "I’m reading a book about anti-gravity. It’s impossible to put down!",
                                    "How did the picture end up in jail?\nIt was framed!",
                                    "My ex-wife still misses me. But her aim is starting to improve!",
                                    "Coffee has a rough time in our house. It gets mugged every single morning!",
                                    "Why was the cookie sad?\nBecause his mom was a wafer long!",
                                    "What’s the difference between a hippo and a zippo?\nOne is really heavy and the other is a little ""lighter!",
                                    "What did the sushi say to the bee?\nWasabee!",
                                    "Why was the baby ant confused?\nBecause all his uncles were ants!",
                                    "I just found out that I’m color blind. The news came completely out of the green!",
                                    "Why didn’t the cat go to the vet?\nHe was feline fine!",
                                    "Who is the penguin’s favorite Aunt?\nAunt-Arctica!",
                                    "What should a lawyer always wear to a court?\nA good lawsuit!",
                                    "The quickest way to make antifreeze?\nJust steal her blanket!",
                                    "How do you make a good egg-roll?\nYou push it down a hill!",
                                    "Apple is designing a new automatic car. But they’re having trouble installing Windows!",
                                    "I’ve started sleeping in our fireplace. Now I sleep like a log!",
                                    "That baseball player was such a bad sport. He stole third base and then just went home!",
                                    "Did you hear about the guy who got hit in the head with a can of soda?\nHe was lucky it was a soft ""drink!",
                                    "The past, the present, and the future walk into a bar. It was tense!",
                                    "You really shouldn’t be intimidated by advanced math… it’s easy as pi!",
                                    "What did the hamburger name it’s baby?\nPatty!",
                                    "One lung said to another, 'we be-lung together!'",
                                    "I asked a Frenchman if he played video games. He said Wii.",
                                    "Why are frogs so happy?\nThey eat whatever bugs them.",
                                    "What did the duck say when she purchased new lipstick?\nPut it on my bill!",
                                    "My parents said I can’t drink coffee anymore. Or else they’ll ground me!",
                                    "What did syrup to the waffle?\nI love you a waffle lot!",
                                    "My wife refuses to go to a nude beach with me. I think she’s just being clothes-minded!",
                                    "Did you hear about that cheese factory that exploded in France?\nThere was nothing left but de Brie!",
                                    "I’m no cheetah, you’re lion!",
                                    "What did the ranch say when somebody opened the refrigerator?\n'Hey, close the door! I’m dressing!'",
                                    "I wanted to take pictures of the fog this morning but I mist my chance. I guess I could dew it ""tomorrow!",
                                    "My dad unfortunately passed away when we couldn’t remember his blood type. His last words to us ""were, 'Be positive!'",
                                    "What do you call a girl with one leg that’s shorter than the other?\nIlene.",
                                    "Towels can’t tell jokes. They have a dry sense of humor.",
                                    "What did the buffalo say to his son?\nBison.",
                                    "Why should you never trust a train?\nThey have loco motives.",
                                    "A cabbage and celery walk into a bar and the cabbage gets served first because he was a head.",
                                    "What’s America’s favorite soda?\nMini soda.",
                                    "What does a clock do when it’s hungry?\nIt goes back for seconds."]
    allResponse["errorWord"] =[     "Please give me a valid input.",
    							    "No, I am not smart enough to do that.",
    							    "Please try again.",
    							    "I do not get that.",
    							    "You mad?",
    							    "You have to ask me again.",
    							     "I cannot give you the answer, sorry.."]
    allResponse["preAnswer"] = [    "Ok Ok Ok.",
    							    "This looks hardish, but I am smart enought to do this.",
    							    "Piece of cake!.",
    							    "Oh too easy.",
    							    "You will thank me for this later.",
    							    "Here you go.",
    							    "There you go.",
    							    "Here are you answers."]
    allResponse["image"] = [        "Wow, supernice image",
    							    "Whose picture is this?",
    							    "What a nice image..",
    							    "Good image you have here",
    							    "Nice Photo !!"]
    #Get Random string from allResponse via key
    @staticmethod
    def GetRandomResponseFromKeys(key):
        i = random.randint(0, len(AllResponse.allResponse[key])-1 )
        return AllResponse.allResponse[key][i]
